server:
  port: 8080
  servlet:
    context-path: /demo13
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 248613

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true
  mapper-locations: classpath:mybatis/mapper/*.xml

knife4j:
  enable: true
  setting:
    # default lang
    language: en-US
    # footer
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Poison02-Java-Study
    # models
    enableSwaggerModels: true
    swaggerModelName: My Models
