server:
  port: 8080
  servlet:
    context-path: /demo19
spring:
  redis:
    host: 127.0.0.1
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    # Redis数据库，这里配置具体使用的数据库
    # database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

