server:
  port: 8080
  servlet:
    context-path: /demo03
# ???????????????????
spring:
  security:
    user:
      name: poison02
      password: 123456

management:
  # ?????????????????????????????
  server:
    port: 8090
    base-path: /sys

  # ????????????never??????always????????????????
  endpoint:
    health:
      show-details: always
  # ??????????????["health", "info"]????*?????????????
  endpoints:
    web:
      exposure:
        include: "*"