server:
  port: 8080
  servlet:
    context-path: /demo15

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false&autoReconnect=true&characterEncoding=utf8&serverTimeZone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 248613
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #最小空闲连接数
      minimum-idle: 5
      # 连接测试query
      connection-test-query: SELECT 1 FROM DUAL
      # 连接池最大连接数，默认是10
      maximum-pool-size: 20
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 30000
      # 连接池名
      pool-name: SpringBootDemoHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 60000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
  sql:
    init:
      platform: mysql
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: true

logging:
  level:
    cdu.zch: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
